
package bpm6.entity

import java.lang.*
import java.math.*
import java.sql.*

data class wfc_process_dto(
       val ID :String,
       var BUSINESSKEY :String? = null,
       var PROCESSDEFID :String? = null,
       var PROCESSDEFVERID :String? = null,
       var CONTROLSTATE :String? = null,
       var PROCESSGROUPID :String? = null,
       var PROCESSTITLE :String? = null,
       var STARTACTIVITYID :String? = null,
       var STARTTASKINSTID :String? = null,
       var STARTTIME :Timestamp? = null,
       var PROCESSPROFILEID :String? = null,
       var PROCESSINSTTYPE :Integer? = null,
       var PARENTPROCESSINSTID :String? = null,
       var PARENTTASKINSTID :String? = null,
       var SECURITYLAYER :Integer? = null,
       var CREATEUSER :String? = null,
       var CREATETIME :Timestamp? = null,
       var CREATEUSERORGID :String? = null,
       var CREATEUSERDEPTID :String? = null,
       var CREATEUSERROLEID :String? = null,
       var CREATEUSERLOCATION :String? = null,
       var ENDACTIVITYID :String? = null,
       var ENDTIME :Timestamp? = null,
       var ISPROCESS :Integer? = null,
       var ISSTART :Integer? = null,
       var ISEND :Integer? = null,
       var ISASYNC :Integer? = null,
       var ISEXCEPTION :Integer? = null,
       var ISOVERTIME :Integer? = null,
       var ISEXISTSUBPROC :Integer? = null,
       var COSTTTIME :BigDecimal? = null,
       var EXPIRETIME :BigDecimal? = null,
       var REMARK :String? = null,
       var IOBD :String? = null,
       var IOR :String? = null,
       var IOS :String? = null,
       var IOC :String? = null,
       var EXT1 :String? = null,
       var EXT2 :String? = null,
       var EXT3 :String? = null,
       var REMINDTIMES :Integer? = null,
       var EXT4 :String? = null,
       var EXT5 :String? = null,
       var EXT6 :String? = null,
       var EXT7 :BigDecimal? = null,
       var EXT8 :BigDecimal? = null
       
)
package bpm6.entity

import java.lang.*
import java.math.*
import java.sql.*

data class wfc_process_dto(
       val ID :String,
       var BUSINESSKEY :String? = null,
       var PROCESSDEFID :String? = null,
       var PROCESSDEFVERID :String? = null,
       var CONTROLSTATE :String? = null,
       var PROCESSGROUPID :String? = null,
       var PROCESSTITLE :String? = null,
       var STARTACTIVITYID :String? = null,
       var STARTTASKINSTID :String? = null,
       var STARTTIME :Timestamp? = null,
       var PROCESSPROFILEID :String? = null,
       var PROCESSINSTTYPE :Integer? = null,
       var PARENTPROCESSINSTID :String? = null,
       var PARENTTASKINSTID :String? = null,
       var SECURITYLAYER :Integer? = null,
       var CREATEUSER :String? = null,
       var CREATETIME :Timestamp? = null,
       var CREATEUSERORGID :String? = null,
       var CREATEUSERDEPTID :String? = null,
       var CREATEUSERROLEID :String? = null,
       var CREATEUSERLOCATION :String? = null,
       var ENDACTIVITYID :String? = null,
       var ENDTIME :Timestamp? = null,
       var ISPROCESS :Integer? = null,
       var ISSTART :Integer? = null,
       var ISEND :Integer? = null,
       var ISASYNC :Integer? = null,
       var ISEXCEPTION :Integer? = null,
       var ISOVERTIME :Integer? = null,
       var ISEXISTSUBPROC :Integer? = null,
       var COSTTTIME :BigDecimal? = null,
       var EXPIRETIME :BigDecimal? = null,
       var REMARK :String? = null,
       var IOBD :String? = null,
       var IOR :String? = null,
       var IOS :String? = null,
       var IOC :String? = null,
       var EXT1 :String? = null,
       var EXT2 :String? = null,
       var EXT3 :String? = null,
       var REMINDTIMES :Integer? = null,
       var EXT4 :String? = null,
       var EXT5 :String? = null,
       var EXT6 :String? = null,
       var EXT7 :BigDecimal? = null,
       var EXT8 :BigDecimal? = null
       
)